#Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'OkinawaPhotoCollection' do
  pod 'RealmSwift'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'PageMenu'

end

target 'OkinawaPhotoCollectionTests' do

end

target 'OkinawaPhotoCollectionUITests' do

end

